### ISSUE TITLE
its present year

### ISSUE THREAD

**Issue by SecondLuke242014** [luk3yx/luk3yx.github.io#8]
# _it is the present year now_.
why 2022?

**Comment by luk3yx** [comment]
The copyright year automatically updates whenever the website is changed, I just haven't changed it in over a year.

**Comment by SecondLuke242014** [comment]
How it updates then?

**Comment by luk3yx** [comment]
The website is made using [Jekyll](https://jekyllrb.com/) which has a current date function:

https://github.com/luk3yx/luk3yx.github.io/blob/65cb7cdb0e0d9d86c239e8276fb9854152bd987b/_includes/smallprint.html#L3

However, GitHub only runs Jekyll whenever there's a commit, and I haven't done anything to the website in over a year so it hasn't had a chance to update itself.

**Comment by SecondLuke242014** [comment]
The copyright year in your web is last year bruh

**Comment by SecondLuke242014** [comment]
Contribute my repo advblocks

**Comment by SecondLuke242014** [comment]
> The website is made using [Jekyll](https://jekyllrb.com/) which has a current date function:
> 
> https://github.com/luk3yx/luk3yx.github.io/blob/65cb7cdb0e0d9d86c239e8276fb9854152bd987b/_includes/smallprint.html#L3
> 
> However, GitHub only runs Jekyll whenever there's a commit, and I haven't done anything to the website in over a year so it hasn't had a chance to update itself.

Use JS instead
